### PR TITLE
lesson 1.3 assignment

### PR DESCRIPTION
**Pull request by podko-va**

### CODE REVIEW

**Comment by mariliah** [comment]
Hey Kate!

The code looks great! Please remember to name the branches after the lessons you are submitting. 
Also you are missing the submit handling in the App.jsx file. Please revise, and re-submit.

It's these set of instructions here:

Handle "Add Todo Form" Submit

- [ ]  Open /src/AddTodoForm.jsx
- [ ]  Add a name attribute to the text input with value title
- [ ]  Inside the AddTodoForm functional component, above the return statement, create a new function called handleAddTodo that takes event as a parameter
- [ ]  First, inside this function, prevent the default behavior of the form submit
- [ ] hint: preventDefault method
- [ ]  Next, retrieve the value of the title element from the event target and store it in a variable named todoTitle
- [ ]  Log the value of todoTitle in the console
- [ ]  Finally, reset the form so the text input value is cleared
- [ ]  Add onSubmit prop to form element and pass the handleAddTodo function by reference
- [ ]  View your application in browser
- [ ]  Enter a value in the text input and submit the form
- [ ]  Verify that the value you entered is visible in the console
- [ ]  Verify that form is cleared properly

**Comment by mariliah** [comment]
Ignore my previous comment! I see it's been added.

I was looking at the wrong branch. I will approve the assignment now.

**Comment by mariliah** [comment]
Please re-submit so that I may approve.

**Comment by podko-va** [comment]
Hi Mariliah!
Could you please clarify me. What do I need to do with 1st week assignment. It's steel in a state "not yet submited".

**Comment by mariliah** [comment]
Hi Kate!

Resubmit, and I will approve it. I'm unsure why it says not yet submitted!

**Comment by podko-va** [comment]
Hi Marilia!

I have re-submitted the assignment for Week 3. Could you please check if it
is correct?

Thank you!

**Comment by mariliah** [comment]
Hi Kate, re-submit it through Airtable so it can be recorded that your assignment was approved after revision.

**Pull request merged**
